export const SET_ADD_FIELD_SELECTED_TYPE = 'SET_ADD_FIELD_SELECTED_TYPE';

export const ADD_SELECT_OPTION = 'ADD_SELECT_OPTION';
export const REMOVE_SELECT_OPTION = 'REMOVE_SELECT_OPTION';

export const SET_TAG_GROUP = 'SET_TAG_GROUP';
