export const SET_ADD_FIELD_SELECTED_TYPE = 'SET_ADD_FIELD_SELECTED_TYPE';
export const SET_ADD_FIELD_DISPLAY_LABEL = 'SET_ADD_FIELD_DISPLAY_LABEL';
export const CLEAR_ADD_FIELD_DISPLAY_LABEL = 'CLEAR_ADD_FIELD_DISPLAY_LABEL';
export const SET_ADD_FIELD_REFERENCE_NAME = 'SET_ADD_FIELD_REFERENCE_NAME';
export const CLEAR_ADD_FIELD_REFERENCE_NAME = 'CLEAR_ADD_FIELD_REFERENCE_NAME';
export const SET_ADD_FIELD_DEFAULT_VALUE = 'SET_ADD_FIELD_DEFAULT_VALUE';
export const CLEAR_ADD_FIELD_DEFAULT_VALUE = 'CLEAR_ADD_FIELD_DEFAULT_VALUE';
